### ISSUE TITLE
addLearningObjectsFromLearningObjectLinkRecords

### ISSUE THREAD

**Issue by wsuchanek** [tobydragon/ConceptKnowledgeCalculator#6]
(List of learning objects, List of learning object link records)

Calls linkLearningObject multiple times

**Comment by wsuchanek** [comment]
Fully tested and implemented, added tests similar to linkLearningObjectsTest() to make sure info was added properly (component test)
1.5 hours

**Comment by tobydragon** [comment]
Assuming test is in ConceptGraphTest, addLearningObjectsFromLearningOBjectLinkREcords. This is really complicated, and not clear how Iactually use this thing. e.g., Why are we creating LearningObjects? Isn't taht supposed to happen automatically from the link record? Otherwise, what is supposed to trigger creation of LearningObjects wehn reading from file?

**Comment by tobydragon** [comment]
It is not clear to me the relationship between addLearningObjectsFromLearningObjectLinkRecords and linkLearningObjects.
